# Copyright 2014 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

sudo: false
language: go
dist: xenial

services:
  - docker

env:
  global:
    # FUZZIT_API_KEY
    secure: "FEm1wF/Ttd5RIvDPg5I/aSAhBWuvkvjmkInFxlVKP4BfLsR1B1ogXV4zKFQiZugyppBta+qP4qP+tSbThSvP9JOCr+/ivnTyYLg/DH1RfQnC7rJmAaZwHGHB+NwblRzU621uIZ4RVvaE391YVJf5519gc+M+bxZ6DO0ScdpbIAVV/7JR9c7Tuvoyi57/MEwAS39k7h83ms8JgRYwuvzpVH9nb6AfYs+CzXuRlsG5mHqFnmzLyG0ewnqh18OoWbyKQwBmM+EoIGmckM8NQZaXWBhEuDP7qdl+QatNfZtK3YwBx2plahBXXMee3NpOAEHOkWxNw1uMb1B8ILDrzrx8oX1A4fF/ZeJl7JLZS/fQUMhDnLG5soA0xaEoAvwhQIHFi3e207rsq9UJsnQlRGhRWzMvx85UR5z+yiur8nVUkogu1DGpH/BPdWbTs+d8behSr7t6Sepo7enjJOPJLz6U67JlP31HvnaLICMEXxJy54BAbdu/47vqFp15lcIMHyDzPltHHWi6uGuRFQPYz8pM5ZAKQ945dO/ZELyEHbjUiLTMFeVoANzahuY56BX6hvsygcOlBWB6ukoJANvxgvM/QYkbh9dMBajYsZqHCWOKRVbBakkqPAUqkBNPOADTp5ZgUwmRySIGzX2X+Efl7cFYZVu+IJl968F8hqYajvS/VCs="

jobs:
  include:
    - stage: Test
      go: 1.12.x
      env: GO111MODULE=on
      cache:
        directories:
          # go1.10+ 'go test' cache on linux (macOS and Windows are # different).
          - $HOME/.cache/go-build
          # go1.11+ with GO111MODULE=on
          - $GOPATH/pkg/mod
          # Cache tools sources. Manually verified that both misspell and ineffassign
          # only depend on the stdlib.
          - $GOPATH/src/github\.com/client9
          - $GOPATH/src/github\.com/gordonklaus
          # For shadow.
          - $GOPATH/src/golang\.org
    - go: 1.8.7
    
    - stage: Fuzz regression
      go: 1.12.x
      dist: bionic
      script:
        - export GO111MODULE="off"
        - go get -u github.com/dvyukov/go-fuzz/go-fuzz github.com/dvyukov/go-fuzz/go-fuzz-build
        - go get -d -v -u ./...
        - wget -q -O fuzzit https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.29/fuzzit_Linux_x86_64
        - chmod a+x fuzzit
        - go-fuzz-build -libfuzzer -o fuzzer.a ./stack
        - clang -fsanitize=fuzzer fuzzer.a -o fuzzer
        - ./fuzzit create job --type local-regression panicparse fuzzer

    - stage: Fuzz
      if: branch = master AND type IN (push)
      go: 1.12.x
      dist: bionic
      script:
        - export GO111MODULE="off"
        - go get -u github.com/dvyukov/go-fuzz/go-fuzz github.com/dvyukov/go-fuzz/go-fuzz-build
        - go get -d -v -u ./...
        - wget -q -O fuzzit https://github.com/fuzzitdev/fuzzit/releases/download/v2.4.29/fuzzit_Linux_x86_64
        - chmod a+x fuzzit
        - go-fuzz-build -libfuzzer -o fuzzer.a ./stack
        - clang -fsanitize=fuzzer fuzzer.a -o fuzzer
        - ./fuzzit create job --type fuzzing panicparse fuzzer

before_script:
  - echo $TRAVIS_GO_VERSION
  - if [[ $TRAVIS_GO_VERSION != 1.8.7 ]]; then go get -u -v github.com/client9/misspell/cmd/misspell github.com/gordonklaus/ineffassign golang.org/x/lint/golint golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow; fi

script:
  # Checks run on the latest version.
  - if [[ $TRAVIS_GO_VERSION != 1.8.7 ]]; then echo 'Check Code is well formatted'; ! gofmt -s -d . | read; fi
  - if [[ $TRAVIS_GO_VERSION != 1.8.7 ]]; then go list ./... | grep -v /vendor/ | xargs -L1 golint -set_exit_status; fi
  - if [[ $TRAVIS_GO_VERSION != 1.8.7 ]]; then go vet ./...; fi
  - if [[ $TRAVIS_GO_VERSION != 1.8.7 ]]; then ineffassign .; fi
  - if [[ $TRAVIS_GO_VERSION != 1.8.7 ]]; then go vet -vettool=$GOPATH/bin/shadow; fi
  - if [[ $TRAVIS_GO_VERSION != 1.8.7 ]]; then bash -c 'set -e; echo "" > coverage.txt; for d in $(go list ./...); do go test -covermode=count -coverprofile=p.out $d; if [ -f p.out ]; then cat p.out >> coverage.txt; rm p.out; fi; done'; fi
  - if [[ $TRAVIS_GO_VERSION != 1.8.7 ]]; then go test -race ./...; fi

  # Check run on older versions.
  - if [[ $TRAVIS_GO_VERSION == 1.8.7 ]]; then go test ./...; fi
  - if [[ $TRAVIS_GO_VERSION == 1.8.7 ]]; then if find . -path ./.git -prune -o -type f -executable -print | grep -e . ; then echo 'Do not commit executables'; false; fi; fi

after_success:
  - if [[ $TRAVIS_GO_VERSION != 1.8.7 ]]; then bash <(curl -s https://codecov.io/bash); fi
